displayName=Seca-Tears
author=STRIKERnz, mayvqt
description=Lowers supported Pick and Harvest crop actions when Magic secateurs are not equipped or in the inventory
tags=Herblore, Reminder, Farming
version=1.0.4
plugins=com.strikernz.secatears.SecaTearsPlugin
build=standard
