displayName=Seca-Tears
author=STRIKERnz, mayvqt
description=Moves supported Pick and Harvest crop actions below Inspect when Magic secateurs are not equipped or in the inventory
tags=Herblore, Reminder, Farming
version=1.1.0
plugins=com.strikernz.secatears.SecaTearsPlugin
build=standard
