displayName=Seca-Tears
author=STRIKERnz
description=Moves Pick and harvest options on Herbs, flowers etc below Inspect when Magic secateurs are not equipped or in the inventory
tags=Herblore, Reminder, Farming
version=1.0
plugins=com.strikernz.secatears.SecaTearsPlugin
build=standard